# Generated by Django 5.1.2 on 2024-10-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(null=True, upload_to='blog_post_images'),
        ),
    ]
